import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, GetCommand, UpdateCommand, PutCommand, DeleteCommand } from "@aws-sdk/lib-dynamodb";
import { getUserFromEvent } from "../shared/auth";
import { success, error } from "../shared/responses";

const ddb = DynamoDBDocumentClient.from(new DynamoDBClient({}));

const IDEAS_TABLE = process.env.IDEAS_TABLE!;
const UPDATES_TABLE = process.env.UPDATES_TABLE!;

export async function handler(event: any) {
  try {
    // 1. Authenticate
    const user = await getUserFromEvent(event);

    // 2. Get ideaId from path parameters
    const ideaId = event.pathParameters?.ideaId;
    if (!ideaId) {
      return error("Missing ideaId in path", 400);
    }

    if (event.httpMethod === "DELETE") {
      await ddb.send(
        new DeleteCommand({
          TableName: IDEAS_TABLE,
          Key: { userId: user.userId, ideaId },
        })
      );

      return success({ message: "Idea deleted" });
    }

    // 3. Fetch idea from DynamoDB
    const ideaResult = await ddb.send(
      new GetCommand({
        TableName: IDEAS_TABLE,
        Key: { userId: user.userId, ideaId },
      })
    );

    const idea = ideaResult.Item;
    if (!idea) {
      return error("Idea not found", 404);
    }

    const now = new Date().toISOString();
    const lastViewedAt = idea.lastViewedAt ?? idea.createdAt ?? now;

    // 4. Calculate time away
    const msAway = Date.now() - new Date(lastViewedAt).getTime();
    const hoursAway = msAway / (1000 * 60 * 60);
    const daysAway = Math.floor(hoursAway / 24);

    // 5. Read persistent report from idea record (generated by surveillance)
    const report = idea.latestReport ?? null;
    const hasReport = report !== null;

    // 6. Update lastViewedAt and mark report as viewed
    await ddb.send(
      new UpdateCommand({
        TableName: IDEAS_TABLE,
        Key: { userId: user.userId, ideaId },
        UpdateExpression: "SET lastViewedAt = :now, reportViewed = :viewed",
        ExpressionAttributeValues: { ":now": now, ":viewed": true },
      })
    );

    // 7. Log viewed event
    await ddb.send(
      new PutCommand({
        TableName: UPDATES_TABLE,
        Item: {
          ideaId,
          timestamp: now,
          type: "viewed",
          summary: `Idea viewed after ${daysAway} day(s) away`,
          daysAway,
        },
      })
    );

    // 8. Return response
    return success({
      idea,
      report,
      hasReport,
      daysAway,
    });
  } catch (err: any) {
    console.error("[IdeaView] Error:", err);
    return error(`Failed to fetch idea: ${err.message}`, 500);
  }
}
